name: doki_websocket_client
description: A websocket client to use in Doki.
version: 2.0.1
repository: https://github.com/rohan031/doki_websocket_client

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
