name: doki_websocket_client
description: A websocket client to use in Doki.
version: 1.0.0
repository: https://github.com/rohan031/doki_websocket_client

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
